newsproject/newsapp/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import auth_login

# app name to use in pairs with urls in templates
app_name = 'newsapp'

# url patterns that gives us resources when requested
# structure is path(string_url, view_name, name=url_name)
urlpatterns = [
    # index (main) page
    path('', IndexView.as_view(), name='index'),

    # getting specific article by this url
    path('articles/article/<int:pk>/', ArticleDetailView.as_view(), name='get_article_by_id'),

    # searching specific word or pattern of text Article table
    path('articles/search/', SearchView.as_view(), name='search_article_by_text'),

    #if search is successful, we redirect the user to the next page
    path('articles/search/<str:text>', SearchSuccessView.as_view(), name='search_success'),

    # getting all articles in ASC order by date
    path('articles/archive/', ArchiveView.as_view(), name='archive'),

    # contacts page url
    path('contacts/', ContactsView.as_view(), name='contacts'),

    # profile page url
    path('profile/', ProfileView.as_view(), name='profile'),

    # profile changing page url
    path('profile/change/', ProfileChangeView.as_view(), name='profile_change'),

    # leave commentary 
    path('articles/article/leavecomment/', LeaveCommentView.as_view(), name='leave_comment'),

    # like commentary 
    path('articles/article/like/', CommentLikeView.as_view(), name='like_comment'),

    # like article
    path('articles/article/like_article/', ArticleDetailView.as_view(), name='like_article'),


    # AUTH PART
    # localhost:8000/login
    path('', auth_login, name="login"),

    # localhost:8000/register
    path("register/", registerView.as_view(), name="registration"),
]

newsproject/newsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls')),
    path('api/', include('project_api.urls')),
    path('api/', include('rest_framework.urls')), # will be added login button
    path('', include('django.contrib.auth.urls')), # login url, logout url
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsproject/newsapp/models.py
from distutils.dep_util import newer_pairwise
from django.db import models
from django.contrib.auth.models import AbstractUser


# Editor model to store editors in database
# Editors table in db.sqlite3
class Editor(models.Model):

    # field to store editor's name
    editor_name = models.CharField(max_length=50)

    # field to store editors's surname
    editor_surname = models.CharField(max_length=50)

    # magic method to retrieve str value of name and surname and
    # return them when the method is called
    def __str__(self) -> str:
        return " ".join((self.editor_name, self.editor_surname))

    def get_name(self):
        return self.editor_name
    
    def get_surname(self):
        return self.editor_surname


# Article model to store editors in database
# Articles table in db.sqlite3
class Article(models.Model):

    # field to store article category
    article_category = models.CharField(max_length=200)

    # field to store artcile name
    article_name = models.CharField(max_length=200)

    # field to store article's text
    article_text = models.TextField()

    # field to store article's date
    article_date = models.DateTimeField(auto_now_add=True)

    # article rating field
    article_rating = models.FloatField(default=0.0)

    # number of views of article
    article_num_of_views = models.IntegerField(default=0)

    # field to store link to editor (foreign key, M to 1 relationship)
    article_editor = models.ForeignKey(Editor, on_delete=models.CASCADE)

    # magic method to retrieve str value of article name and
    # return it when the method is called
    def __str__(self) -> str:
        return self.article_name

    # each time this article is opened
    # its number will be increased
    def increase_view_num(self):
        self.article_num_of_views += 1

    # number of likes of article
    def article_rate(self, newrate):
        self.article_rating += newrate

    def get_article_rating(self):
        return self.article_rating

    def get_article_num_of_views(self):
        return self.article_num_of_views

# this is extension of exising class in django.contrib.auth.models.AbstractUser
# it is slightly different from what we had before for superuser (admin)
# we have added user_avatar field to store some image
# Users table in db.sqlite3
class CustomUser(AbstractUser):

    # field to store user picture
    user_avatar = models.ImageField(upload_to="user_avatars/", default='NULL')

    # returning username when called
    def __str__(self) -> str:
        return self.username


# This model is used to store comments on articles that will be left by CustomUsers (Users)
# Comments table in db.sqlite3
class Comment(models.Model):

    # field to store comment text
    comment_text = models.TextField('comment_text')

    # field to store date of comment
    comment_date = models.DateTimeField('comment_date', auto_now_add=True)

    # field to store rating of comment
    comment_rating = models.FloatField(default=0.0)

    # field to store a link to an article
    comment_on_article = models.ForeignKey(Article, on_delete=models.CASCADE)

    # field to store a link to a user
    comment_owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    # returning comment text and its owner when called
    def __str__(self) -> str:
        return " ".join((str(self.id), self.comment_on_article.article_name))

    # TO-DO
    def rate_comment(self, newrate):
        self.comment_rating += newrate

newsproject/newsapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *

class CustomUserForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email','username', 'user_avatar')


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ('email','username', 'user_avatar')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["comment_text", "comment_owner", "comment_on_article"]

newsproject/newsapp/views.py
from urllib import request
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import *
from django.views.generic.edit import CreateView
from django.views.generic import *
from .forms import *
from django.db.models import CharField, TextField
from django.db.models import Q


# Create your views here.
# Generic CBV for Index page
class IndexView(ListView):
    template_name = "newsapp/index.html"
    context_object_name = "latest_articles"
    queryset = Article.objects.order_by('-article_date')

    # adding additional context to already existing context above
    def get_context_data(self, **kwargs):
        # getting existing context value (latest_articles here rn)
        context = super().get_context_data(**kwargs)
        # adding popular articles
        context['popular_articles'] = Article.objects.filter(
            article_num_of_views__gt=100).order_by('-article_num_of_views')[:4]
        # adding categories
        context['categories'] = Article.objects.values(
            "article_category").distinct()
        # context['arts_by_cats'] = Article.objects.filter() # TO-DO
        return context

# Generic CBV for Article page


class ArticleDetailView(DetailView):
    model = Article
    template_name = "newsapp/article.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        article = Article.objects.get(pk=kwargs['object'].id)
        article.increase_view_num()
        article.save()
        context = super().get_context_data(**kwargs)
        context["latest_articles"] = Article.objects.order_by('-article_date')
        context['popular_articles'] = Article.objects.filter(
            article_num_of_views__gt=100).order_by('-article_num_of_views')[:4]
        art_category = kwargs['object'].article_category
        context['related_articles'] = Article.objects.filter(
            article_category=art_category).order_by('-article_num_of_views')[:8]
        context['form'] = CommentForm()
        context['comments_on_article'] = Comment.objects.filter(
            comment_on_article=kwargs['object'].id)
        context['categories'] = Article.objects.values(
            "article_category").distinct()
        return context

    def post(self, request):
        if request.method == 'POST':
            article_rate = request.POST.get('article_rate')
            article = Article.objects.get(id=request.POST.get('article_id'))
            article.article_rate(float(article_rate))
            article.save()
            return redirect("newsapp:get_article_by_id",
                            pk=request.POST.get('article_id'))


# Custom class based view for searching any matching text in Article table
class SearchView(View):
    paginated_by = 5
    # overriding post method to accept request.POST and work with its content

    def post(self, request):
        try:
            if request.method == "POST" and len(request.POST.get("search_field")) > 0:
                searching_text = request.POST.get("search_field")
                return redirect("newsapp:search_success", text=searching_text)
            else:
                return render(request, "newsapp/search.html",
                              {"empty_res": "There is no article"})
        except Exception as e:
            print(e)
            return render(request, "newsapp/search.html",
                          {"empty_res": f"No articles have been found by {request.POST.get('search_field')}"})


# Custom class based view for successful search
class SearchSuccessView(View):

    # override get() method to return successful result
    # if any matching was in Article table
    def get(self, request, text):

        # getting fields that are either CharField
        # or TextField to search later in these fields
        fields = [field for field in Article._meta.fields if isinstance(
            field, CharField) or isinstance(field, TextField)]

        # list of querysets using Q class. Logic is field.name might be either
        # article_category, name or text which corresponds to the fields above
        queries = [Q(**{field.name + "__icontains": text}) for field in fields]
        # print(fields[0].name)
        qs = Q()
        for query in queries:
            # here is queryset which might be equal to next values
            # (AND: ('article_category__icontains', 'str_text_here'))
            # (OR: ('article_category__icontains', 'str_text_here'),
            #       ('article_name__icontains', 'str_text_here'))
            # (OR: ('article_category__icontains', 'str_text_here'),
            #       ('article_name__icontains', 'str_text_here'),
            #       ('article_text__icontains', 'str_text_here'))
            qs = qs | query

        # getting result filtering by qs (querysets)
        # that have been created above
        search_res = Article.objects.filter(qs)
        return render(request, "newsapp/search.html",
                      {"search_res": search_res, "empty_res": "There is no article"})


# Generic CBV for Archive of articles
class ArchiveView(ListView):
    template_name = 'newsapp/archive.html'
    context_object_name = "archive_articles"
    queryset = Article.objects.all()[:100]  # 2235
    paginate_by = 10

# Generic CBV for Contacts page


class ContactsView(TemplateView):
    template_name = "newsapp/contacts.html"

# Generic CBV for Profile page


class ProfileView(TemplateView):
    template_name = "newsapp/user_page.html"

# Generic CBV for Profile changing page


class ProfileChangeView(FormView):
    template_name = "registration/user_change_page.html"
    form_class = CustomUserChangeForm

# Generic CBV for Registration page


class registerView(CreateView):
    form_class = CustomUserForm
    success_url = reverse_lazy('login')
    template_name = 'newsapp/registration.html'

# Generic CBV for leaving comments on Article


class LeaveCommentView(View):

    def post(self, request):
        if request.method == 'POST':
            comment_on_article = request.POST.get('comment_on_article')
            new_comment = Comment(comment_text=request.POST.get('comment_text'),
                                  comment_owner=CustomUser.objects.get(
                id=request.user.id),
                comment_on_article=Article.objects.get(id=comment_on_article))
            new_comment.save()
            return redirect("newsapp:get_article_by_id",
                            pk=request.POST.get('comment_on_article'))


class CommentLikeView(View):
    def post(self, request):
        if request.method == 'POST':
            comment_rate = request.POST.get('comment_rate')
            comment_obj = Comment.objects.get(
                id=request.POST.get('comment_id'))
            comment_obj.rate_comment(float(comment_rate))
            comment_obj.save()
            return redirect("newsapp:get_article_by_id",
                            pk=request.POST.get('article_id'))

newsproject/newsapp/templates/newsapp/archive.html
{% extends 'newsapp/layout.html'%}
{% load static %}
{% block page_title %} Arhive Page {%endblock%}

{%block top_news%}
<div class="top-news">
    <div class="container">
    {% if archive_articles %}
    {% for art in page_obj %}
    
    <div class="row">
    <ol start="{{forloop.counter}}">
        <li><a href="{% url 'newsapp:get_article_by_id' art.id %}"> {{art.article_name}}</a></li>
    </ol>
    </div>
    {%endfor%}

    {% else %}
    <h2> NO ARCHIVE ARTICLES </h2>
    {%endif%}
    <span class="step-links">
        {% if page_obj.has_previous %}
            <b><a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a></b>
        {% endif %}

        <span class="current">
            <i> {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</i>
        </span>

        {% if page_obj.has_next %}
            <b> <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></b>
        {% endif %}
</div>
</div>
{% endblock %}

newsproject/newsapp/templates/newsapp/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <title>{% block page_title %} {% endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap News Template - Free HTML Templates" name="keywords">
        <meta content="Bootstrap News Template - Free HTML Templates" name="description">

        <!-- Favicon -->
        <link href="{% static 'newsapp/img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet"> 

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'newsapp/lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'newsapp/lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'newsapp/css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top Bar Start -->
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="tb-contact">
                            <p><i class="fas fa-envelope"></i>info@aitunews.kz</p>
                            <p><i class="fas fa-phone-alt"></i>+7 777 777 77 77</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="tb-menu">
                            <a href="">About</a>
                            <a href="">Privacy</a>
                            <a href="">Terms</a>
                            <a href="">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar Start -->
        
        <!-- Brand Start -->
        <div class="brand">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-4">
                        <div class="b-logo">
                            <a href="{% url 'newsapp:index' %}">
                                <img src="{% static 'newsapp/img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4">
                        <div class="b-ads">
                            <a href="https://github.com/shynggys9219">
                                <img src="{% static 'newsapp/img/ad.gif' %}" alt="Ads" style="width:250px;height:80px;">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4">
                        <div class="b-search">
                            <form class="" action="{%url 'newsapp:search_article_by_text' %}" method="post">
                                {% csrf_token %}
                                <input type="text" name="search_field" value="" method='POST' placeholder="Search here" required>
                                <!-- <input type="submit" name="Search" value="Search"> -->

                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Brand End -->

        <!-- Nav Bar Start -->
        <div class="nav-bar">
            <div class="container">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'newsapp:index' %}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'newsapp:contacts' %}" class="nav-item nav-link">Contacts</a>
                            <a href="{% url 'newsapp:archive' %}" class="nav-item nav-link">Archive</a>
                            {% if user.is_authenticated %}
                            <a href="{% url 'newsapp:profile' %}" class="nav-item nav-link">{{user.username}}</a>
                            {% if user.is_staff %}
                            <a href="{% url 'admin:index' %}" class="nav-item nav-link">Manage</a>
                            {%endif%}
                            <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                            {% else %}
                            <a href="{% url 'login' %}" class="nav-item nav-link">Sign In</a>
                            {%endif%}
                        </div>
                        <div class="social ml-auto">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        {% block main_content%}
        <!-- Top News Start-->
        {% block top_news %}
                    {% block top_with_container %}
                    
                    {% endblock %}
                    
        {% endblock %}
        <!-- Top News End-->

        {% block news_by_categories %}
        <!-- Category News Start-->
        {% endblock %}
                    
        <!-- Category News End-->

        <!-- Category News Start-->
        <!-- Main News End-->
        {% endblock %}
        <!-- Footer Start -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>Astana IT University</p>
                                <p><i class="fa fa-envelope"></i>info@astanait.edu.kz</p>
                                <p><i class="fa fa-phone"></i>I do not remember the phone number</p>
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Useful Links</h3>
                            <ul>
                                <li><a href="#">Lorem ipsum</a></li>
                                <li><a href="#">Pellentesque</a></li>
                                <li><a href="#">Aenean vulputate</a></li>
                                <li><a href="#">Vestibulum sit amet</a></li>
                                <li><a href="#">Nam dignissim</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Quick Links</h3>
                            <ul>
                                <li><a href="#">Lorem ipsum</a></li>
                                <li><a href="#">Pellentesque</a></li>
                                <li><a href="#">Aenean vulputate</a></li>
                                <li><a href="#">Vestibulum sit amet</a></li>
                                <li><a href="#">Nam dignissim</a></li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Newsletter</h3>
                            <div class="newsletter">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed porta dui. Class aptent taciti sociosqu
                                </p>
                                <form>
                                    <input class="form-control" type="email" placeholder="Your email here">
                                    <button class="btn">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Menu Start -->
        <div class="footer-menu">
            <div class="container">
                <div class="f-menu">
                    <a href="">Terms of use</a>
                    <a href="">Privacy policy</a>
                    <a href="">Cookies</a>
                    <a href="">Accessibility help</a>
                    <a href="">Advertise with us</a>
                    <a href="">Contact us</a>
                </div>
            </div>
        </div>
        <!-- Footer Menu End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="">Some Company Name</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'newsapp/lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'newsapp/lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'newsapp/js/main.js' %}"></script>
    </body>
</html>

newsproject/newsapp/templates/newsapp/registration.html
{% extends "newsapp/layout.html"%}


{%block main_content%}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{%url 'newsapp:index'%}">Home</a></li>
            <li class="breadcrumb-item active">Registration</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Contact Start -->
<div class="contact">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="contact-form">
                  <h3>Registration Form</h3>
                    <form method="post">
                      {% csrf_token %}
                        <div class="form-row">
                          <table class="form-group col-md-6">
                          {%for field in form %}
                            <div class="form-group col-md-6">
                                <tr>
                                  <td>{{field.label}} </td>
                                  <td> {{field}}</td>
                                </tr>
                                <tr></tr>
                            </div>
                            {%endfor%}
                          </table>
                        </div>
                        <div>
                          <!-- <a href=""></a> -->
                          <button class="btn" type="submit">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{%endblock%}

newsproject/newsapp/templates/newsapp/search.html
{% extends "newsapp/layout.html"%}
{%block page_title%} Search Results {%endblock%}
{% block top_news %}
<div class="top-news">
  <div class="container">
      
      
    {% for article in search_res%}
    <div class="row">
      <ol>
        <li value="{{forloop.counter}}">
          <a href="{% url 'newsapp:get_article_by_id' article.id %}">
          {{article.article_name}}
        </a>
        </li>
      </ol>
  </div>
      {% empty %}
      {{empty_res}}
      {%endfor%}
 
  </div>
</div>
{% endblock%}

newsproject/newsapp/templates/newsapp/user_page.html
{% extends "newsapp/layout.html" %}
{% block page_title %}
  {{ user.username }}
{% endblock %}
{%load static%}

{% block main_content %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
  <div class="container">
      <ul class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'newsapp:index' %}">Home</a></li>
          <li class="breadcrumb-item active">{{user.username|title}}</li>
      </ul>
  </div>
</div>
<!-- Breadcrumb End -->

<!-- Single News Start-->
<div class="single-news">
  <div class="container">
      <div class="row">
          <div class="col-lg-8">
            {% if user %}
              <div class="sn-container">
                  <div class="sn-content">
                      <h1 class="sn-title"> {{user.username|title}} </h1>
                      <p>Name: {{user.username|title}}</p>
<p>Email: {{user.email}}</p>
<p>User Image: <img src="{{user.user_avatar.url}}" alt="" width="200" height="200"></p>
<p>Dob: {{user.last_login}}</p>
<p>User IMG URL: {{user.user_avatar.url}}</p>
<p><a href="{% url 'newsapp:profile_change' %}">Change User Info</a></p>
                      
                      
                  </div>
              </div>
              {% else %}
              <p>No such user </p>
              {%endif%}
          </div>

      </div>
  </div>
</div>
<!-- Single News End-->
{% endblock %}